sudo: required
services:
  - docker

before_install:
  - docker build -t yashkhurana/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true yashkhurana/react-test npm test

after_success:
  - docker build -t yashkhurana/multi-client ./client
  - docker build -t yashkhurana/multi-nginx ./nginx
  - docker build -t yashkhurana/multi-server ./server
  - docker build -t yashkhurana/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push yashkhurana/multi-client
  - docker push yashkhurana/multi-nginx
  - docker push yashkhurana/multi-server
  - docker push yashkhurana/multi-worker